In [1]:
import numpy as np

In [18]:
# EJERCICIO 1

# Actividades
# 1. Convierte la lista en un array de NumPy y reorganízalo como una matriz de 4 × 6.
# 2. Muestra su tipo de dato, número de dimensiones y forma.
# 3. Calcula el total vendido en cada turno y el total vendido de cada producto.
# 4. Identifica el turno con mayor cantidad total de ventas.
# 5. Obtén una copia con todas las ventas incrementadas en 2 unidades y verifica que la matriz original no
# cambió.

ventas = [
    18, 12, 25, 10, 8, 15,
    20, 14, 22, 13, 11, 17,
    16, 19, 27, 9, 12, 18,
    24, 17, 21, 15, 10, 20
]

ventas_matriz = np.array(ventas)
# 1
ventas_matriz = ventas_matriz.reshape((4, 6))

# 2
print(ventas_matriz.dtype) # tipo de dato
print(ventas_matriz.ndim) # numero de dimensiones
print(ventas_matriz.shape) # filas x columnas
print('-'*100)

# 3
venta_total_turno = ventas_matriz.sum(axis=1)
print(venta_total_turno)
print('-'*100)

venta_total_producto = ventas_matriz.sum(axis=0)
print(venta_total_producto)
print('-'*100)

# 4
print(venta_total_turno.argmax())
print('-'*100)

# 5
ventas_incrementadas = ventas_matriz.copy()
ventas_incrementadas += 2
print(ventas_matriz)
print(ventas_incrementadas)


int64
2
(4, 6)
----------------------------------------------------------------------------------------------------
[ 88  97 101 107]
----------------------------------------------------------------------------------------------------
[78 62 95 47 41 70]
----------------------------------------------------------------------------------------------------
3
----------------------------------------------------------------------------------------------------
[[18 12 25 10  8 15]
 [20 14 22 13 11 17]
 [16 19 27  9 12 18]
 [24 17 21 15 10 20]]
[[20 14 27 12 10 17]
 [22 16 24 15 13 19]
 [18 21 29 11 14 20]
 [26 19 23 17 12 22]]


In [34]:
# Ejercicio 2

stock = np.array(
    [
        [25, 18, 30, 12, 20],
        [14, 22, 16, 28, 19],
        [35, 17, 24, 15, 21]
    ]
)

ventas = np.array(
    [
        [10, 20, 12, 8, 7],
        [16, 10, 18, 9, 20],
        [15, 19, 8, 17, 11]
    ]
)

# Actividades
# 1. Calcula el inventario restante mediante una operación entre matrices.
stock_restante = stock - ventas
print(stock_restante)
print('-'*100)

# 2. Localiza los valores negativos, que representan ventas mayores al stock disponible.
mascara = stock_restante < 0
print(stock_restante[mascara])
print('-'*100)

# 3. Crea una copia corregida en la que los valores negativos sean reemplazados por 0.
stock_restante_corregido = stock_restante.copy()
stock_restante_corregido[mascara] = 0
print(stock_restante_corregido)
print('-'*100)

# 4. Calcula el stock restante total por categoría antes y después de la corrección.
stock_restante_antes = stock_restante.sum(axis=1)
print(stock_restante_antes)

stock_restante_despues = stock_restante_corregido.sum(axis=1)
print(stock_restante_despues)
print('-'*100)

# 5. Determina la categoría con mayor stock disponible después de la corrección.
print(stock_restante_despues.argmax() + 1)

[[15 -2 18  4 13]
 [-2 12 -2 19 -1]
 [20 -2 16 -2 10]]
----------------------------------------------------------------------------------------------------
[-2 -2 -2 -1 -2 -2]
----------------------------------------------------------------------------------------------------
[[15  0 18  4 13]
 [ 0 12  0 19  0]
 [20  0 16  0 10]]
----------------------------------------------------------------------------------------------------
[48 26 42]
[50 31 46]
----------------------------------------------------------------------------------------------------
1


In [62]:
# Ejercicio 3

precios = np.array([
    [4.5, 6.0, 3.5, 8.0],
    [4.7, 5.8, 3.6, 8.2],
    [4.6, 6.1, 3.4, 7.9]
])

unidades = np.array([
    [30, 18, 42, 15],
    [25, 20, 35, 17],
    [28, 22, 40, 14]
])

# 1. Calcula la facturación por producto y sucursal mediante multiplicación elemento a elemento.
total = precios * unidades
print(total)

# 2. Calcula la facturación total de cada sucursal y la facturación total de cada producto.
total_sucursal = total.sum(axis=1)
total_producto = total.sum(axis=0)
print(total_sucursal)
print(total_producto)
print('-'*100)

# 3. Identifica la sucursal con mayor facturación.
print(total_sucursal.argmax() + 1)
print('-'*100)

# 4. Encuentra el valor máximo de facturación individual y su posición dentro de la matriz.
valor_maximo = total.max()
print(valor_maximo)

for fila in range(total.shape[0]):
    for columna in range(total.shape[1]):
        if valor_maximo == total[fila, columna]:
            print(fila, columna)
print('-'*100)

# 5. Obtén la transpuesta de la matriz de facturación e interpreta qué representan ahora sus filas.
print(total.T)

[[135.  108.  147.  120. ]
 [117.5 116.  126.  139.4]
 [128.8 134.2 136.  110.6]]
[510.  498.9 509.6]
[381.3 358.2 409.  370. ]
----------------------------------------------------------------------------------------------------
1
----------------------------------------------------------------------------------------------------
147.0
0 2
----------------------------------------------------------------------------------------------------
[[135.  117.5 128.8]
 [108.  116.  134.2]
 [147.  126.  136. ]
 [120.  139.4 110.6]]


In [2]:
import numpy as np

In [22]:
# Ejercicio 4

notas = np.array(
    [
        [14, 16, 13, 15],
        [18, 17, 16, 19],
        [11, 13, 12, 14],
        [16, 15, 17, 16],
        [13, 10, 15, 12]
    ]
)

# print(notas.shape)

# 1. Calcula el puntaje total y el promedio de cada estudiante sin usar np.mean.
# puntaje_total = np.sum(notas, axis=1)
puntaje_total = notas.sum(axis=1)
print(puntaje_total)

promedio = notas.mean(axis=1)
print(promedio)

promedio_sin_mean = puntaje_total / notas.shape[1]
print(promedio_sin_mean)

print("-" * 100)

# 2. Identifica al estudiante con mayor promedio.
mejor_estudiante = promedio.argmax() + 1
print(mejor_estudiante)
print("-" * 100)

# 3. Calcula el total acumulado de cada evaluación y determina cuál tuvo menor rendimiento global.
puntaje_total_materia = notas.sum(axis=0)
print(puntaje_total_materia)

menor_rendimiento_materia = puntaje_total_materia.argmin() + 1
print(menor_rendimiento_materia)
print("-" * 100)

# 4. Filtra todas las notas menores que 13.
mascara = notas > 13
notas_mayores_13 = notas[mascara]
print(notas_mayores_13)
print("-" * 100)

# 5. Crea una copia y reemplaza las notas menores que 13 por 13; luego recalcula los promedios.
notas_copia = notas.copy()
mascara = notas < 13
notas[mascara] = 13

promedios_corregidos = notas.mean(axis=1)
print(notas_copia)
print(notas)
print("-" * 100)

print(promedio)
print(promedios_corregidos)

[58 70 50 64 50]
[14.5 17.5 12.5 16.  12.5]
[14.5 17.5 12.5 16.  12.5]
----------------------------------------------------------------------------------------------------
2
----------------------------------------------------------------------------------------------------
[72 71 73 76]
2
----------------------------------------------------------------------------------------------------
[14 16 15 18 17 16 19 14 16 15 17 16 15]
----------------------------------------------------------------------------------------------------
[[14 16 13 15]
 [18 17 16 19]
 [11 13 12 14]
 [16 15 17 16]
 [13 10 15 12]]
[[14 16 13 15]
 [18 17 16 19]
 [13 13 13 14]
 [16 15 17 16]
 [13 13 15 13]]
----------------------------------------------------------------------------------------------------
[14.5 17.5 12.5 16.  12.5]
[14.5  17.5  13.25 16.   13.5 ]


In [34]:
# Ejercicio 5
pasajeros = np.array(
    [
        [120, 135, 128, 142, 150, 180, 175],
        [95, 102, 110, 108, 115, 130, 125],
        [160, 155, 170, 168, 172, 190, 185],
        [80, 88, 92, 100, 105, 118, 112]
    ]
)

# 1. Calcula el total semanal de cada ruta.
total_semanal_por_ruta = pasajeros.sum(axis=1)
print(total_semanal_por_ruta)
print("-"*100)

# 2. Calcula el total de pasajeros por día considerando todas las rutas.
total_pasajeros_por_dia = pasajeros.sum(axis=0)
print(total_pasajeros_por_dia)
print("-"*100)

# 3. Identifica la ruta con mayor total semanal y el día con mayor demanda global.
ruta_con_mayor_total_semanal = total_semanal_por_ruta.argmax() + 1
dia_con_mayor_demanda = total_pasajeros_por_dia.argmax() + 1
print(ruta_con_mayor_total_semanal)
print(dia_con_mayor_demanda)
print("-"*100)

# 4. Extrae mediante slicing únicamente los datos del fin de semana (dos últimas columnas).
print(pasajeros)
datos_fin_semana = pasajeros[:, -2:]
print(datos_fin_semana)
print("-"*100)

# 5. Ordena una copia de los totales semanales de menor a mayor.
total_semanal_por_ruta_copia = total_semanal_por_ruta.copy()
total_semanal_por_ruta.sort()

print(total_semanal_por_ruta_copia)
print(total_semanal_por_ruta)

[1030  785 1200  695]
----------------------------------------------------------------------------------------------------
[455 480 500 518 542 618 597]
----------------------------------------------------------------------------------------------------
3
6
----------------------------------------------------------------------------------------------------
[[120 135 128 142 150 180 175]
 [ 95 102 110 108 115 130 125]
 [160 155 170 168 172 190 185]
 [ 80  88  92 100 105 118 112]]
[[180 175]
 [130 125]
 [190 185]
 [118 112]]
----------------------------------------------------------------------------------------------------
[1030  785 1200  695]
[ 695  785 1030 1200]


In [63]:
# Ejercicio 11

# Se registraron lecturas de dos máquinas durante tres días, con cuatro mediciones por día. Los
# datos deben organizarse como un tensor de forma (2, 3, 4).

lecturas = [
    42, 45, 44, 47, 43, 46, 48, 45, 44, 47, 49, 46,
    51, 50, 53, 52, 49, 54, 55, 52, 50, 53, 56, 54
]

# 1. Convierte la lista en un tensor con forma (2, 3, 4) y muestra sus dimensiones.
lecturas_tensor = np.array(lecturas).reshape((2, 3, 4))
print(len(lecturas))
print(lecturas_tensor.shape)
print(lecturas_tensor)
print("-"*100)

# 2. Obtén todas las lecturas de la segunda máquina.
segunda_maquina_data = lecturas_tensor[1]     #lecturas_tensor[1, :, :]
print(segunda_maquina_data)
print("-"*100)

# 3. Calcula el total de lecturas por máquina realizando sumas por ejes.
total_por_dia = lecturas_tensor.sum(axis=2)
print(total_por_dia)

total_por_maquina = total_por_dia.sum(axis=1)
print(total_por_maquina)
print("-"*100)

# lecturas_tensor.sum(axis=(2, 1))

# 4. Encuentra el valor máximo global y su posición dentro del tensor convertido temporalmente en un vector.
# vector = np.array(lecturas)
vector = lecturas_tensor.reshape(lecturas_tensor.size)
print(vector)
max_global = vector.max()
print(max_global)

posicion = vector.argmax()
print(posicion)
print("-"*100)

# 5. Reorganiza el tensor como una matriz de 6 × 4, donde cada fila represente un día de una máquina.
lecturas_tensor_reorganizado = lecturas_tensor.reshape((6, 4))
print(lecturas_tensor_reorganizado.shape)
print(lecturas_tensor_reorganizado)

24
(2, 3, 4)
[[[42 45 44 47]
  [43 46 48 45]
  [44 47 49 46]]

 [[51 50 53 52]
  [49 54 55 52]
  [50 53 56 54]]]
----------------------------------------------------------------------------------------------------
[[51 50 53 52]
 [49 54 55 52]
 [50 53 56 54]]
----------------------------------------------------------------------------------------------------
[[178 182 186]
 [206 210 213]]
[546 629]
----------------------------------------------------------------------------------------------------
[42 45 44 47 43 46 48 45 44 47 49 46 51 50 53 52 49 54 55 52 50 53 56 54]
56
22
----------------------------------------------------------------------------------------------------
(6, 4)
[[42 45 44 47]
 [43 46 48 45]
 [44 47 49 46]
 [51 50 53 52]
 [49 54 55 52]
 [50 53 56 54]]


In [72]:
# Ejercicio 12

agua = np.array(
    [
        [420, 380, 450, 400, 390],
        [510, 480, 495, 505, 470],
        [360, 340, 375, 355, 365],
        [460, 440, 430, 455, 445]
    ]
)

# Actividades
# 1. Convierte el array a tipo float64.
agua_float = agua.astype(np.float64)     #.astype('float64')
print(agua.dtype)
print(agua_float.dtype)
print(agua_float)
print("-"*100)

# 2. Calcula la nueva matriz de consumo aplicando una reducción de 12%.
consumo = agua_float * 0.88
print(consumo)
print("-"*100)

# 3. Calcula los litros ahorrados por parcela y el ahorro total.
ahorro = agua_float - consumo
print(ahorro)

ahorro_total = ahorro.sum()
print(ahorro_total)
print("-"*100)

# 4. Identifica la parcela que ahorra más agua.
ahorro_por_parcela = ahorro.sum(axis=1)
print(ahorro_por_parcela)

parcela_mas_ahorrativa = ahorro_por_parcela.argmax() + 1
print(parcela_mas_ahorrativa)
print("-"*100)

# 5. Filtra las zonas cuyo consumo original fue mayor que 450 litros.
zonas_mayores450 = agua_float[agua_float > 450]
print(agua_float > 450)
print(zonas_mayores450)


int64
float64
[[420. 380. 450. 400. 390.]
 [510. 480. 495. 505. 470.]
 [360. 340. 375. 355. 365.]
 [460. 440. 430. 455. 445.]]
----------------------------------------------------------------------------------------------------
[[369.6 334.4 396.  352.  343.2]
 [448.8 422.4 435.6 444.4 413.6]
 [316.8 299.2 330.  312.4 321.2]
 [404.8 387.2 378.4 400.4 391.6]]
----------------------------------------------------------------------------------------------------
[[50.4 45.6 54.  48.  46.8]
 [61.2 57.6 59.4 60.6 56.4]
 [43.2 40.8 45.  42.6 43.8]
 [55.2 52.8 51.6 54.6 53.4]]
1023.0000000000001
----------------------------------------------------------------------------------------------------
[244.8 295.2 215.4 267.6]
2
----------------------------------------------------------------------------------------------------
[[False False False False False]
 [ True  True  True  True  True]
 [False False False False False]
 [ True False False  True False]]
[510. 480. 495. 505. 470. 460. 455.]


In [92]:
# Ejercicio 16

# Contexto. Un laboratorio necesita construir una matriz base de 5 × 5. Todos los valores parten de 10, pero
# la diagonal principal representa puntos de calibración y debe valer 110.
# Datos iniciales
# Construye la matriz únicamente con np.ones, np.eye y operaciones aritméticas.


# Actividades
# 1. Crea la matriz solicitada sin escribir manualmente sus 25 valores.
matriz_base = np.ones((5, 5)) * 10
matriz_diagonal = np.eye(5) * 100
matriz_final = matriz_base + matriz_diagonal
print(matriz_final)
print("-"*100)

# 2. Calcula las sumas por fila y por columna.
suma_por_fila = matriz_final.sum(axis=1)
suma_por_cols = matriz_final.sum(axis=0)
print(suma_por_fila)
print(suma_por_cols)
print("-"*100)

# 3. Comprueba mediante una operación que la matriz es igual a su transpuesta.
mascara = matriz_final == matriz_final.T
print(mascara.sum() == matriz_final.size)
print("-"*100)

# 4. Obtén sus valores mínimo y máximo.
val_max = matriz_final.max()
val_min = matriz_final.min()
print(val_min, val_max)
print("-"*100)


# 5. Convierte la matriz a tipo int y muestra el tipo de dato final.
matriz_int = matriz_final.astype(np.uint8)
print(matriz_int)
print(matriz_int.dtype)

[[110.  10.  10.  10.  10.]
 [ 10. 110.  10.  10.  10.]
 [ 10.  10. 110.  10.  10.]
 [ 10.  10.  10. 110.  10.]
 [ 10.  10.  10.  10. 110.]]
----------------------------------------------------------------------------------------------------
[150. 150. 150. 150. 150.]
[150. 150. 150. 150. 150.]
----------------------------------------------------------------------------------------------------
True
----------------------------------------------------------------------------------------------------
10.0 110.0
----------------------------------------------------------------------------------------------------
[[110  10  10  10  10]
 [ 10 110  10  10  10]
 [ 10  10 110  10  10]
 [ 10  10  10 110  10]
 [ 10  10  10  10 110]]
uint8
