In [1]:
import numpy as np

print(np.__version__)

2.5.1


In [2]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a)

[[1 2 3]
 [4 5 6]]


In [3]:
a.shape

(2, 3)

In [4]:
a.dtype

dtype('int64')

In [5]:
a.ndim

2

### CREANDO ARRAYS

In [8]:
vector_unos = np.ones(10, dtype='int64')
print(vector_unos)

[1 1 1 1 1 1 1 1 1 1]


In [9]:
matriz_unos = np.ones((3, 3), dtype='int64')
print(matriz_unos)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [10]:
matriz_zeros = np.zeros((5, 5))
print(matriz_zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

In [12]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [13]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
np.full((3, 3), 9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [18]:
matriz = np.full((2, 5), 8.1)
print(matriz)
print("="*10)
matriz_zeros_como = np.zeros_like(matriz)
print(matriz_zeros_como)

[[8.1 8.1 8.1 8.1 8.1]
 [8.1 8.1 8.1 8.1 8.1]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [28]:
np.empty((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.full(5, 1.4)

array([1.4, 1.4, 1.4, 1.4, 1.4])

In [30]:
np.full(5, 1.4).astype(int)

array([1, 1, 1, 1, 1])

In [31]:
np.full(5, 7, dtype=str)

array(['7', '7', '7', '7', '7'], dtype='<U1')

In [41]:
# Crea un array con los números del 10 al 50 de 5 en 5.
array = np.arange(10, 50, 5)
print(array)
print("=" * 100)

# Imprime shape, ndim, dtype y size.
print(array.shape)
print(array.ndim)
print(array.dtype)
print(array.size)
print("=" * 100)

# Crea una matriz 3×4 llena de ceros y otra 3×3 identidad.
matriz_zeros = np.zeros((3, 4))
identidad = np.eye(3)
print(matriz_zeros)
print(identidad)
print("=" * 100)

# Genera 7 valores equiespaciados entre -1 y 1.
arr = np.linspace(-1, 1, 7)
print(arr)
print("=" * 100)

# Convierte el primer array a float32 y comprueba itemsize antes y después.
array_flotante = array.astype('float32')
print(array_flotante.dtype)
print(array_flotante.itemsize)

[10 15 20 25 30 35 40 45]
(8,)
1
int64
8
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[-1.         -0.66666667 -0.33333333  0.          0.33333333  0.66666667
  1.        ]
float32
4


In [46]:
arr = np.arange(0, 16, 1)
matriz = arr.reshape((4, 4))
print(matriz)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [47]:
matriz[1, 1]

np.int64(5)

In [49]:
matriz[1, :]

array([4, 5, 6, 7])

In [51]:
matriz[:, 3]

array([ 3,  7, 11, 15])

In [53]:
matriz[-1, -1]

np.int64(15)

In [58]:
vector = np.arange(0, 10, 1)
print(vector)
vista = vector[6:]
print(vista)

vista[-1] = 1000
print(vista)

[0 1 2 3 4 5 6 7 8 9]
[6 7 8 9]
[   6    7    8 1000]


In [59]:
print(vector)

[   0    1    2    3    4    5    6    7    8 1000]


In [60]:
vector = np.arange(0, 10, 1)
print(vector)
vista = vector[6:].copy()
print(vista)

vista[-1] = 1000
print(vista)

[0 1 2 3 4 5 6 7 8 9]
[6 7 8 9]
[   6    7    8 1000]


In [61]:
print(vector)

[0 1 2 3 4 5 6 7 8 9]


In [62]:
a = np.array([1.0, 4.0, 9.0])

np.clip(a, 2, 5)

array([2., 4., 5.])

In [65]:
a = np.array([1.0, 4.0, 9.0, np.nan, np.nan, np.nan, 50, 50])

np.isnan(a).sum()

np.int64(3)

In [74]:
np.isclose(4, 6, 10)

np.True_

In [79]:
array = np.array([1,2,3,5])

In [80]:
array.max()

np.int64(5)

In [81]:
array.argmax()

np.int64(3)